// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  window.GAME = new Phaser.Game({
    antialias: false,
    height: 2000,
    width: 800,
    state: {
      init: function() {
        var debug;
        debug = this.game.debug;
        debug.font = "20px monospace";
        debug.lineHeight = 25;
        this.game.forceSingleUpdate = false;
      },
      create: function() {
        this.obj = {
          boolean: true,
          date: new Date,
          "function": function() {},
          nan: NaN,
          "null": null,
          number: Math.PI,
          object: {},
          regexp: /:-}/,
          string: ":-(",
          undefined: void 0,
          point: new Phaser.Point,
          rect: new Phaser.Rectangle,
          image: this.make.image()
        };
        this.stanza = ["Twas brillig, and the slithy toves", "Did gyre and gimble in the wabe:", "All mimsy were the borogoves,", "And the mome raths outgrabe."];
      },
      update: function() {},
      render: function() {
        var debug, x, y;
        debug = this.game.debug;
        x = 20;
        y = 20;
        debug.object(this.obj, x, y, {
          color: "auto",
          label: "color: 'auto'",
          sort: true
        });
        debug.object(this.stanza, x, y += 400, {
          label: "array"
        });
        debug.object(this.game, x, y += 200, {
          color: "auto",
          label: "game",
          sort: true
        });
      },
      shutdown: function() {}
    }
  });

}).call(this);
